### ISSUE TITLE
Focusdag 6: desk research (data pods, data spaces, Vlaams datanuts bedrijf & verifiable credentials)

### ISSUE THREAD

**Issue by kad-michij** [kadaster-labs/solid-quest#10]
desk research (data pods, data spaces, Vlaams datanuts bedrijf & verifiable credentials)

**Comment by kad-michij** [comment]
De afgelopen week veel gesprekken gevoerd over Solid & onze demonstrator (oa met [GIDS Open standaarden](https://www.gidsopenstandaarden.org/); & [Digita](https://www.digita.ai/)) en aanwezig geweest op de [Trefdag van Digitaal Vlaanderen](https://www.vlaanderen.be/trefdag-digitaal-vlaanderen). Naar aanleiding daarvan weer wat "desk research" gedaan. 

Data pods vs data spaces -> zie readme

In het gesprek met **GIDS Open Standaarden** werd oa verwezen naar:
- [Nuts](https://nuts.nl/) & [Gitbook Nuts](https://nuts-foundation.gitbook.io/drafts)/ & [Github Nuts](https://github.com/nuts-foundation) 
“Nuts is een initiatief dat ervoor zorgt dat zorgverleners digitaal kunnen samenwerken. Als basis hanteren we een set uitgangspunten, die we hebben gevat in een [manifest](https://nuts.nl/manifest). Iedere partij die zich kan vinden in deze uitgangspunten kan zich aansluiten bij Nuts. Op basis van deze uitgangspunten verzamelen en ontwikkelen we open standaarden voor samenwerking. Die open standaarden implementeren we vervolgens in onze Open Source “Nuts node”.”
Verschillende componenten; OAuth2, Distributed Network, Decentralized Identifiers (DID), Verifiable Credential, IRMA.. 
- [Sovrin](https://sovrin.org/) & [Github Sovrin](https://github.com/sovrin-foundation/sovrin) 
"Sovrin’ most commonly refers to the Sovrin Network, a public service utility enabling self-sovereign identity on the Internet. The Sovrin Network is decentralized, meaning individuals can collect, hold, and choose which identity credentials —such as a driver’s license or employment credential—without relying on individual siloed databases that manage the access to those credentials. Sovrin is an open source project that offers the tools and libraries to create private and secure data management solutions that then run on Sovrin’s identity network.”
- [KIK-V](https://www.kik-v.nl/het-programma-kik-v) & [Gitlab KIK-V](https://kik-v.gitlab.io/#slide=1 )
“Het programma Keteninformatie Kwaliteit Verpleeghuiszorg, KIK-V, draagt bij aan de verbetering van de gegevensuitwisseling over kwaliteit in de verpleeghuiszorg. Binnen KIK-V werken instellingen voor verpleeghuiszorg (als aanbieder) en andere partijen met een publieke taak (als afnemer) samen om deze gegevensuitwisseling effectiever en efficiënter te maken.”

**Trefdag Digitaal Vlaanderen**

- [Het Vlaams Datanutsbedrijf](https://www.vlaanderen.be/digitaal-vlaanderen/het-vlaams-datanutsbedrijf) - met name oprichting van het Vlaams Datanutsbedrijf erg interessant
- Ze werken concreet aan 2 use cases binnen het project "My Professional Data"; het het delen van je diploma (met Randstad) en loongegevens (zie ook de filmpjes op hun site)
- Werken hiervoor samen met [Inrupt](https://inrupt.com/) (podprovider en met name gericht op grotere organisaties). Hierdoor kan elke Vlaamse(?) burger een persoonlijke datakluis krijgen waar ze data in kunnen laden en van waaruit ze data kunnen delen met partijen. 
- Ze werken met verifiable credentials & presentations die ze wegschrijven in de pod. Met een attestatie service kan de afnemer controleren of de verifiable credential (nog) geldig is. Ik kan niet vinden welke techniek oid ze hiervoor gebruiken, alleen dat [MAGDA](https://overheid.vlaanderen.be/informatie-vlaanderen/producten-diensten/gegevensdelingsplatform-magda) hier ook bij wordt gebruikt. MAGDA; is volgens mij hun eigen gegevensdelingsplatform
- Belangrijke vraag; waarom verstrekt de authentieke bron (na toestemming betrokkene) niet zelf de data aan de ontvanger/afnemer zoals Randstad? 
- Vraag; Ze noemen vaak de OSLO-standaarden. Zij die bij ons ook bekend?
- Vraag; hoe voorkom je dat een burger straks 100 verschillende persoonlijke kluizen heeft? (de overheid komt met een kluis, je zorgverzekeraar, je notaris ([Izimi](https://www.izimi.be/nl/) in België ) etc.
- NB: de burger kan in dit geval niet zelf zijn pod provider kiezen. De pod wordt verstrekt door de overheid en alleen door de overheid goedgekeurde/toegevoegde data bronnen kunnen worden gebruikt. 

![image](https://user-images.githubusercontent.com/62643510/192805740-a031d93b-5282-4a6a-a3fe-df264e86fe0d.png)

**Verifiable credentials**
- [W3 model Verifiable Credentials](https://www.w3.org/TR/vc-data-model/)  - veel informatie en voorbeelden te vinden, ook hoe een JSON LD bestand bijv. opgebouwd dient te worden 
- [Github Sphereon Verifiable Credentials](https://github.com/Sphereon-Opensource/rn-vc-js) 

![image](https://user-images.githubusercontent.com/62643510/192806037-bf97c219-b55d-43c4-99da-932284fe8ed7.png)

**Comment by marcvanandel** [comment]
Dit is mooie en waardevolle info ... die niet in een issue verborgen zou moeten blijven ... maar in een ... `achtergronden.md` of zo? 🤔

**Comment by marcvanandel** [comment]
✅ [Background.md](https://github.com/kadaster-labs/solid-quest/blob/main/Background.md)
