### ISSUE TITLE
VerKadasteren van deze repo

### ISSUE THREAD

**Issue by NickvApeldoorn** [kadaster-labs/solid-quest#19]
- [x] Verplaatsen naar [github.com/kadaster-labs](https://github.com/kadaster-labs) Org
- [ ] Oppoetsen van README plus Background.md
- [x] Tegel 'Solid Quest' op [labs.kadaster.nl](https://labs.kadaster.nl/thema/innovatie) (met verwijzing naar deze repo)
- [x] Verplaatsen van repo communiceren aan onze contacten
- [x] redirect repo [hier](/marcvanandel/solid-quest) achterlaten

**Comment by NickvApeldoorn** [comment]
@marcvanandel zoekt even uit hoe de organisatie van rechten is op github.com/kadaster-labs

**Comment by marcvanandel** [comment]
@NickvApeldoorn , @kad-rowla , @kad-michij , @kad-busses , de repo is verplaatst en jullie toegang wordt geregeld ... be patient 😄

**Comment by kad-kostej** [comment]
Jullie hebben (na acceptatie van de invitation in jullie Kadaster mailbox) nu allemaal toegang tot de betreffende repository.

**Comment by marcvanandel** [comment]
Redirect lijkt door GitHub al gerealiseerd ... Zo lang het niet kapot is, is het niet nodig een andere redirect in te stellen (door bijv. een nieuwe repo (in [/marcvanandel](/marcvanandel)) achter te laten waarin de verwijzing handmatig wordt gepubliceerd)

**Comment by marcvanandel** [comment]
Oppoetsen in #21
