### ISSUE TITLE
Review van LD events

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/solid-quest#23]
Kloppen de events in LD formaat?

**Comment by kad-busses** [comment]
Wilde je nog iets met dit issue?

**Comment by marcvanandel** [comment]
Review ... is klaar als we aannemen dat SolidOS (de browser) het valide vindt ... OK?

**Comment by marcvanandel** [comment]
Veelvuldig gereviewd en verbeterd. De demo werkt ondertussen incl. navigeren mbv de SolidOS browser en een GitHub hook voor de validatie van LD files. Dat is voldoende review en controle van de LD content en events
