### ISSUE TITLE
Deployment van Docker Solid PODs met voorbeeld data (tbv demonstrator)

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/solid-quest#24]
Gaan we deployen op Azure (uiteraard obv infrastructure as code)? Of gaan we deployen op MAP (en hoe dan)?

**Comment by kad-busses** [comment]
Vooralsnog alleen lokaal, met Docker Compose. Deployment geeft extra werk, onderhoud en lopende kosten, wat we allemaal niet erbij moeten willen
