### ISSUE TITLE
Events als Verifiable Credentials opslaan

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/solid-quest#25]
- oorspronkelijke data integriteit 'verzekering'
- oorsprong van de data 'verzekering'

**Comment by kad-busses** [comment]
https://github.com/kadaster-labs/solid-quest/issues/13 omschrijft wat VCs zijn en waar die inzetbaar/nodig zijn. Het uitdelen van het eigendomsbewijs door het Kadaster en identiteitsbewijs door de overheid is geïndentificeerd in dat issue. Wat nog niet duidelijk is of de events in VCs gevat moeten worden en hoe dat er dan uit ziet.

Waarom events überhaupt opslaan als verifiable credential? Het uitgangspunt van (Solid) PODs is dat je zelf de regie hebt over de data. Dus wie daar bij kan, maar ook wat daar precies in staat. Hoewel het opslaan van het onderhandelen in events er historie en herleidbaarheid aan geven zijn ze nog steeds kwetsbaar voor wijzigingen. Er staat de eigenaar van de POD niets in de weg om biedingen (events) uit het verleden te herschijven. Dit ondermijnt (potentieel) de integriteit van de data en daarmee het vertrouwen in het proces. Door events te combineren met VCs geeft het als het ware een "echtheidscertificaat" aan zowel de uiteindelijke koopovereenkomst, als de tussengelegen events waaruit die koopovereenkomst is opgebouwd.

**Comment by kad-busses** [comment]
Het is niet toereikend om de (kale) events op te slaan in de eigen POD, om bovengenoemde reden. Er zijn verschillende ontwerpen denkbaar hoe we Verifiable Events (VE) kunnen maken. 

Ontwerp #1
Middels de Koopovereenkomst app (KOEK App) creëer je een event die in je eigen POD wordt opgeslagen. Ook geef je een VC uit aan de ander, welke in diens POD wordt opgeslagen. Dit leidt er effectief toe dat de events dubbel worden opgeslagen. In je POD beschik je aan het einde van het proces over je eigen events en de (gesigneerde) events van de ander.

Ontwerp #2
Variatie op ontwerp #1, alleen wordt hierbij enkel de proof of een hash van je event opgeslagen in de aggregate van de ander.

Ontwerp #3
Het dubbel opslaan van gegeven kan verkomen worden door de events enkel bij de ander op te slaan. Jij doet immers een bod aan de ander, het event kan daardoor (door jou ondertekend) opgeslagen worden bij de ander. Dit voelt echter tegenstrijdig met het principe dat je zelf over je eigen data beschikt.

Ontwerp #4
Het is ook mogelijk om een (neutrale) derde partij te introduceren: "De Digitale Makelaar". Deze makelaar legitimeert de biedingen/events door ze te ondertekenen. Dit kan gerealiseerd worden als een backend waar de KOEK App mee praat. Het plaatsen van een bod wordt dan voorzien van een ondertekening van de digitale makelaar. De andere partij kan de events uit jou PODs op deze manier verifiëren bij de makelaar.

Ontwerp #5
Koper en verkoper zouden zelf hun events kunnen ondertekenen, maar dan de events elders kunnen opslaan, in een gedeelde omgeving. Bijvoorbeeld een (huis)kluis of een omgeving die klaargezet is door de makelaar.

**Comment by kad-busses** [comment]
In dit ontwerp zijn er een aantal verschillende VCs:
- credentials uitgegeven door Kadaster / Overheid
- ondertekende events tijdens onderhandelingsproces
- access control zodat koper en verkoper bij elkaar (private) events kunnen. Die willen we immers niet publiekelijk beschikbaar maken

**Comment by kad-busses** [comment]
Ah check, de term 'aggregate' deed me aan event sourcing denken, 'aggregate administratie' zet (mij) daardoor op het verkeerde been 😇. Dit gaat over de _event metadata_, dus iets als: verkooplogboek (VLB)? 

> Open staand punt: Hoe weet de koper dat deze lijst niet door de verkoper is aangepast en dus of die wel compleet is?

Dit vind ik een interessante. Het uitgangspunt van Solid / pods is dat je zelf de beheer over je data hebt (toch?). Verschuiven we dit nu niet naar: data _over_ jou wordt _bij_ jou opgeslagen? Of eigenlijk: in hoeverre gaat dit over trust?

We kunnen natuurlijk alle interactie (events, VLB) laten signen door een makelaar, maar op welk punt hadden we die data niet beter in een makelaar pod kunnen opslaan? Gezien de events, logboek en koopovereenkomst over meerdere partijen gaat.

> * Nog anders ... ?

Nou ja, events en logboek dus bij "een digitale makelaar" in de pod opslaan. Koper/verkoper hebben beiden dan alleen lees en append rechten. Weten ze beiden zeker dat de andere partij het niet gewijzigd heeft en heb je voor dit stukje geeneens VCs nodig. Het eindproduct (de koopovereenkomst) kan (als VC?) bij koper en verkoper in pod opgeslagen worden.
