### ISSUE TITLE
Notificaties bij updates (vooral van andere partij)

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/solid-quest#26]

**Comment by kad-busses** [comment]
Dit kan op basis van [Linked Data Notifications (LDN)](https://www.w3.org/TR/ldn/). Hiermee is interactie tussen verschillende users mogelijk. Zijn wel demos hier en daar te vinden van Solid + LDN.

![image](https://github.com/kadaster-labs/solid-quest/assets/56066664/2107348b-2d32-4f6c-8bdc-2b66d1b6d6e0)
