### ISSUE TITLE
SolidJS Framework

### ISSUE THREAD

**Issue by kad-busses** [kadaster-labs/solid-quest#28]
SolidJS Framework is naar Beta: https://www.solidjs.com/blog/introducing-solidstart. 

Hoewel we al een begin hebben gemaakt met Next.js lijkt het SolidJS framework goed aan te sluiten bij wat we proberen te doen. Het is ontworpen met als uitgangspunt om aan te sluiten op Solid Pods. Kan het uit om over te stappen?

- Uitvoeren van (klein) onderzoekje of het framework goed / beter aansluit bij onze use-case

**Comment by marcvanandel** [comment]
LDflex blijft nodig om LinkedData op te halen uit endpoints - meer in de stijl van JavaScript objecten a.k.a. 'developer style' - en daar (met de opgehaalde gegevens) 'magic' mee doen zoals events ophalen en tot een koopovereenkomst document transformeren.

SolidJS is met name een alternatief voor de nu gebruikte solid-ui-react componenten incl. authenticatie en session management? Dit laatste moeten we nog uitzoeken 😁

**Comment by kad-busses** [comment]
<p float="left" align="middle">
<img src="https://solidproject.org/assets/img/solid-emblem.svg" width="100"/>
<img src="https://cdn-icons-png.flaticon.com/512/43/43312.png" width="25"/>
<img src="https://www.solidjs.com/assets/logo.123b04bc.svg" width="100"/>
</p>

OK. Ben er ondertussen achter dat het om verschillende dingen gaat. SolidJS is enkel een nieuw shiny frontend framework, welke niks met Solid te maken heeft. 🙈

Sluit dus niet per se aan bij wat we doen. Inrupt heeft de solid client libraries als Javascript [beschikbaar](https://docs.inrupt.com/developer-tools/javascript/) gemaakt, waardoor we SolidJS zouden kunnen gebruiken, maar we kunnen net zo goed bij React/Next.js blijven. Daar heeft Inrupt immers ook componenten voor ontwikkeld. Daar kunnen we voor nu dus beter gebruik van blijven maken.

**Comment by marcvanandel** [comment]
😆 what's in a name, right? 🙈
