### ISSUE TITLE
VC issuer BRP Koper Koos

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/solid-quest#33]
Als gemeente B wil ik de persoonsgegevens van Koper Koos 'issue'n als VC. Deze moeten worden opgeslagen in de POD van Koper Koos.

**Comment by kad-busses** [comment]
Werkt. Backend service kan VCs issuen. Koopovereenkomst app slaat die voor je op in de Pod. Werkt voor Koos, en iedere andere Solid Pod (waarvoor het WebId is aangemeld bij de backend)
