### ISSUE TITLE
VC issuer Kadaster eigendomsrecht van perceel door Verkoper Vera

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/solid-quest#34]
Als Kadaster wil ik het eigendomsrecht van perceel (met object ID xxx) door Verkoper Vera 'issue'n. Deze wil ik uitgeven aan Verkoper Vera zodat zij deze kan opslaan in haar POD.

**Comment by kad-busses** [comment]
Ik begrijp nog niet helemaal hoe we de taxonomie van ZVG kunnen gebruiken. Ik ben denk ik op zoek naar een (machine leesbare) overzicht van de termen binnen ZVG. Is die ook ergens? De definities op https://taxonomie.zorgeloosvastgoed.nl/ worden telkens per stuk via een API call opgehaald. 

Voor de VCs zelf maken we nu bijvoorbeeld gebruik van de `@context` https://www.w3.org/2018/credentials/v1

**Comment by kad-busses** [comment]
Of, met andere woorden, hoe kan ik de ZVG LD termen gebruiken? 😇

**Comment by kad-busses** [comment]
Thanks! Mooi overzicht, dat helpt zeker.

Publiceren hoeft wat mij betreft eerst niet, denk dat het voor de quest niet per se nodig is. Ik voeg nu verwijzingen toe als bijvoorbeeld `http://kad.zorgeloosvastgoed.nl/id/concept/Eigendom` voor Eigendom. Dan hebben we in elk geval al wel de link naar Zorgeloos Vastgoed 🙂

**Comment by kad-busses** [comment]
In de demo wordt nu een Eigendoms VC uitgegeven. Heb 'm nog iets uitgebreid, er zit nu ook pand informatie in, waar er eerst alleen perceelinformatie is. Dingen zoals adres zijn iets leesbaarder voor in de demo 😉
```json
{
    "webID": "http://localhost:3001/verkoper-vera/profile/card#me",
    "eigendom": {
        "perceel": {
            "begrenzingPerceel": "",
            "kadastraleGrootte": "42",
            "identificatie": 10020263270000
        },
        "pand": {
            "adres": "Laan van Westenenk 701",
            "postcode": "7334 DP",
            "woonplaats": "Apeldoorn"
        }
    }
}
```
