### ISSUE TITLE
VC verifier Kadaster van ingeschreven koopovereenkomst

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/solid-quest#36]
Als Kadaster wil ik de VC getekende koopovereenkomst verifiëren als deze aangeboden wordt ter inschrijving in de openbare registers door de notaris (of misschien wel koper, terwijl de notaris wel de issuer van deze VC blijft (uiteraard))

**Comment by kad-busses** [comment]
Buiten scope van de demonstrator
