### ISSUE TITLE
Eindpresentatie opleveren

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/solid-quest#42]
Een super toffe video waarin we in verschillende stukjes onze Solid Quest beschrijven:

- [x] Overzicht van onze Quest
- [x] Concepten met demo van de demonstrator
  - [x] Linked Data
  - [x] Solid PODs
  - [x] Event Sourcing
  - [x] VCs
  - [x] Data minimalisatie
- [x] Ervaringen
  - [x] LDflex
  - [x] Inrupt vs Community Solid Server
  - [x] Volwassenheid van specs en tools
- [x] Demo !!
- [ ] Blog
- [ ] Video
- [ ] Live eindpresentatie

**Comment by kad-michij** [comment]
+ blog/presentatie?!

**Comment by kad-michij** [comment]
Plus filmpje/demonstrator op labs.kadaster.nl

**Comment by marcvanandel** [comment]
Eindpresentatie is vergevorderd (final?) Ervaringen zijn niet zo expliciet opgenomen maar in algemene termen: 'tech is nog in ontwikkeling' Voorbeelden daarvan zijn libraries die in verschillende staat zijn en ook specifieke versies van de specs ondersteunen. Dat geldt zowel voor de SOLID spec als voor de VC spec.

Demo runsheet is ook uitgewerkt.

- [ ] Blog en 
- [x] Video en 
- [x] Live eindpresentatie

wordt nog aan gewerkt ...

**Comment by kad-busses** [comment]
Video staat live, heb een linkje ernaar aan de README toegevoegd 📺
