### ISSUE TITLE
VC Revocating

### ISSUE THREAD

**Issue by kad-busses** [kadaster-labs/solid-quest#44]
Hoe werkt dat precies? Er is een Verifiable Credential Status List in ontwerp: https://w3c.github.io/vc-status-list-2021/

> This specification describes a privacy-preserving, space-efficient, and high-performance mechanism for publishing the status information associated with Verifiable Credentials.

En, willen we dit ook demonstreren?

**Comment by kad-michij** [comment]
@kad-busses Ik denk dat het voor het Kadaster best interessant is om te onderzoeken (bijv. het intrekken van een eigendomstitel) maar ik heb geen idee hoe complex dit is. Heb jij daar al een beeld van? Ligt er al iets van werkende code en/of is het nog erg in ontwikkeling?

**Comment by kad-busses** [comment]
Eens, het concept is zeker relevant voor het Kadaster als issuer. 

Ja en ja, er is iets van code en het is nog erg in ontwikkeling, zo staat ergens in de spec:
> This document is experimental and is undergoing heavy development. It is inadvisable to implement the specification in its current form. An [experimental implementation](https://github.com/digitalbazaar/vc-status-list) is available.

Mijn (voorlopige) indruk is dat voor de solid-quest twee mogelijkheden voor zijn:
1. Het Kadaster kan een API endpoint aanbieden `/status/{credentialID}`. Hiermee negeren we de Verifiable Data Registry en moet je altijd terug naar de Issuer om de status op te vragen
2. De eerder genoemde Status List. Dit is de richting waar het W3C op gaat en is de 'nette' manier

Met optie 1 kunnen we wellicht wat sneller laten zien dat een VC revoked kan zijn, al is de implementatie dan niet in de spirit van VC 😇

Denk dat dit onderwerp erg geschikt is om tijdens een focus-dag verder in te duiken 😁

**Comment by kad-busses** [comment]
Onderwerp is ingedoken. Zie bijvoorbeeld https://github.com/kadaster-labs/solid-quest/issues/48#issuecomment-1432895597. In de documentatie is een stukje toegevoegd over revocation onder [Background.md#verifiable-data-registry](https://github.com/kadaster-labs/solid-quest/blob/main/Background.md#verifiable-data-registry). Wordt niet toegevoegd aan de demo
