### ISSUE TITLE
Je persoonlijke testament pod

### ISSUE THREAD

**Issue by RaymondKroon** [kadaster-labs/solid-quest#50]
Het het is handig als bij overlijden je digitale testament vrijgeeft aan personen die je zelf kunt instellen. Hiervoor zou je een koppeling met de BRP gemaakt kunnen worden. De pod krijgt een melding (alle meldingen?) over de eigenaar, en ontsluit de pod bij overlijden.

Als een pod ook als identicatie provider werkt kan hierna ook ingelogd worden bij bepaalde websites, zoals Facebook. Facebook opzeggen vanuit het account zelf is veel makkelijker, dan het via Facebook regelen. Misschien past dit ook wel een beetje bij het idee dat je eigenaar bent van je eigen data: je nabestaanden kunnen zelf actie ondernemen zonder afhankelijk te zijn van eventuele overleden services van de social media of andere webdiensten.

(Als dit te regelen is via de BRP kun je dit ook koppelen aan wachtwoord managers misschien. Of de datapod moet ook een wachtwoordservice zijn)

**Comment by marcvanandel** [comment]
Wat een leuk idee ... en mogelijk relevant ... maar niet voor onze Solid Quest. Blijft leuk en toch sluiten voor onze queste
