### ISSUE TITLE
Offline data

### ISSUE THREAD

**Issue by RaymondKroon** [kadaster-labs/solid-quest#52]
Nu we #51 hebben, kunnen we ook data helemaal niet meer op de pod zetten. Dit beschermt extra tegen hacken.

Als er bijvoorbeeld een verzoek komt tot een kopie van een indentiteitsbewijs, dan kun je deze eenmalig terugsturen. Ook als het bewijs digitaal is kun je het eenmalig beschikbaarstellen. Dus er is geen harde koppeling op de pod met overheidsdiensten, want hoewel het lekker gemakkelijk is, is het ook een risico.

**Comment by marcvanandel** [comment]
Het is inderdaad de vraag wat er in een _online_ datakluis zou 'moeten' staan en wat (ook) in een _offline_ datakluis kan staan. In de ontwikkeling van wallets en datakluizen lopen discussies hierover door elkaar en zijn vaak niet scherp. Het is de vraag of een online datakluis helemaal geen toegevoegde waarde heeft ... of zelfs (vooral) negatieve effecten voor de burger. Wie zal het zeggen?

Open punt dat nog ontwikkeld en ontdekt zal (moeten) worden ...
