### ISSUE TITLE
Het risico van gevalideerde data. Is er een alternatief?

### ISSUE THREAD

**Issue by RaymondKroon** [kadaster-labs/solid-quest#53]
Eén van de voorbeelden van de persoonlijke datakluis is gevalideerde loongegevens, voor bijvoorbeeld het aanvragen van een lening. Want we zijn allemaal tegen frauderen toch?

Ik ben van mening dat we niet deze kant op moeten gaan. Moet je je droomhuis ontzegt worden omdat je net van baan bent gewisseld en er op je gevalideerde data staat dat je geen vast contract hebt? Of omdat je 10 euro te weinig per maand salaris krijgt?  Moet een bank voor uitmaken wat wel en niet mag? Of wat als je werkgever klein is en nog niet meedoet aan het systeem, moet je dan maar ergens anders gaan werken? Of hopen dat ze het gaan implementeren?

Ook is er het risico van een glijdende schaal. Nu leggen we vast dat gevalideerde loongegevens niet gebruikt mogen in sollicitatieproceduren. Maar werkgeversorganisaties zullen zeer waarschijnlijk gaan lobbyen dat ze die data willen gebruiken. Zodat ze een gepaste aanbieding kunnen doen. Dit betekent dat eens een sloeber, altijd een sloeber, want je krijgt er elke keer maar een beetje bij. In salarisonderhandelingen is over het algemeen de werknemer al in het nadeel, dus laten we er niet een nog grote nadeel van maken.

Op dit moment kan ik mij geen alternatief bedenken welke wel kan gaan werken. Hierdoor vraag ik mij ook af of alle slimmigheden met een datapod wel een goed idee zijn. Ik denk dat hoe dommer we de pod houden hoe beter. Een persoonlijke plek voor je fotoboek voor familie is super handig, maar ook niet meer dan dat.  Je datapod met bijbehorden online id is een goed initiatief om een tegengeluid te geven aan de grote social media platforms nu. En wie weet, een goed alternatief voor email. Misschien is dat alles wat het zou moeten zijn: je eigen online plekje voor (digitale) communicatie. En voor de rest blijf alles lekker zoals het nu is.

**Comment by marcvanandel** [comment]
Adresseren met #78
