### ISSUE TITLE
Verifiable Data Registry

### ISSUE THREAD

**Issue by kad-michij** [kadaster-labs/solid-quest#54]
(namens @NickvApeldoorn )

In het artikel [Self Sovereign Identity: wat elke internet jurist zou moeten weten](https://research.vu.nl/en/publications/self-sovereign-identity-wat-elke-internet-jurist-zou-moeten-weten) wordt de werking van Self Sovereign Identity, als manier om invulling te geven aan de Europese Digitale Identiteit, uitgelegd. Een Verifiable Data Registry speelt hier een cruciale rol in. 

_Idealiter zou er een decentraal beheerd, onveranderlijk en openbaar register zijn waarin de metadata van uitgegeven credentials als anonieme gegevens voor iedereen te raadplegen zijn. Wanneer een holder VCs deelt, kan de verifier aan de hand van de aangeleverde VC in het register nagaan of de issuer bevoegd is om een dergelijke VC uit te geven, dit ook daadwerkelijk heeft gedaan voor de desbetreffende holder, of de VC voldoet aan de eisen én of deze nadien niet herroepen is._ Volgens de auteurs lijkt een Blockchain ideaal voor dit register en zij wijzen op de [European Blockchain Services Infrastructure (EBSI)](https://ec.europa.eu/digital-building-blocks/wikis/display/EBSI/Home) die reeds in ontwikkeling is. 

De EBSI kent verschillende usecases, waaronder de Verifiable Credentials Use Case Family. _all Verifiable Credentials have in common that they are based on a self-sovereign information sharing pattern where the Holders (subjects) of credentials are in control of how, when, and by whom their information is verified, via an EBSI Conformant wallet._ 

- Kunnen wij dus concluderen dat alle experimenten rond de EDI-wallet, waaronder die in Nederland, werken aan een EBSI Conformant wallet? 

Binnen dit self-sovereign information sharing pattern is er, naast de bekende issuers, holders en verifiers, nog een vierde actor. _The trust in the exchange is mediated by Trusted Accreditation Organisations who record the Trusted Issuers' accreditations on the ledger._ 

- Betekent dit dat een Trusted Accreditation Organisation verifiert dat het Kadaster een bevoegde issuer is van VC’s en het bewijs in de Verifiable Data Registry plaatst? 

en/of 

- Betekent dit dat een Trusted Accreditation Organisation het bewijs van / de metadata over een uitgegeven VC door het Kadaster in de Verifiable Data Registry plaatst?

**Comment by NickvApeldoorn** [comment]
Tijdens de [IRMA Meetup](https://www.youtube.com/watch?v=jZIzLmnBB98) van 30 september 2022 vertelt Laurens Debackere van het Agentschap Digitaal Vlaanderen over de manier waarop zij omgaan met identiteit & authenticatie in het Solid Ecosysteem. Een Verifiable Data Registry speelt hier ook een rol in. Hieronder volgt een samenvatting.

**Interactie met Solid**
In hun oplossing zien zij twee manieren van interactie met Solid:
- Solid als gegevensbron. In dit geval interacteer je met Solid als verifier.
- Solid als kanaal (voor de overheid) om authentieke data beschikbaar te stellen. In dit geval interacteer je met Solid als issuer.

**Identiteit in het Solid ecosysteem**
“Waarschijnlijk zullen burgers (vele) verschillende datakluizen hebben." Deze kluizen worden verbonden aan de hand van een identifier (WebID). Een WebID geeft o.a. aan hoe een persoon zich gaat authenticeren. Het beschrijft de link met de identity provider. In het geval van Vlaanderen moet deze identity provider voldoen aan de eIDAS. Let op: één gebruiker kan verschillende WebIDs hebben. Er wordt nog onderzocht hoe deze WebIDs verbonden kunnen worden, zonder dat dit inzichtelijk is (voor mensen die daar geen toestemming voor hebben gekregen).

Ook hoopt Vlaanderen op één frontend / portal waarmee burgers toegang hebben tot al hun datakluizen.

**Verifiable Credentials**
In de Vlaamse oplossing worden geen representaties gesigned maar echt de triples / ruwe data zelf. Autentieke data wordt door een issuer omgezet in een VC, gesigned en in een POD opgeslagen. Het bewijs dat een VC is uitgegeven (de metadata) komt in een Verifiable Data Registry, beheerd door [MAGDA](https://overheid.vlaanderen.be/informatie-vlaanderen/producten-diensten/gegevensdelingsplatform-magda). Dit register werkt met een public key infrastructure en revocation list.

Toestemming voor toegang tot een POD (autorisaties) worden ook omgezet in een VC. 

VCs worden gelinkt aan een WebID als identifier. Let op: de issuer is verantwoordelijk voor de koppeling tussen een VC en persoon(sgegevens). Een VC kan dus toegekend worden aan een verkeerd persoon.

**Conclusie**
De presentatie heeft bij ons twee vragen opgeroepen:
- Aangezien iemand meerdere WebIDs kan hebben, wil je tenaamstelling opnemen in de (Kadaster) VC?
- Er zijn dus verschillende manieren om tot een Verifiable Data Registry te komen, ook zonder gebruik te maken van EBSI?

**Comment by kad-michij** [comment]
Tijdens een discussie kwam de term Verifiable Data Registry weer voorbij en merkten we dat we niet helemaal scherp hadden wat dit nou precies is.

Wat is precies de rol van de Verifiable Data Registry (VDR)? En wat voor data wordt daar bijv. opgeslagen? 

Na het bekijken van verschillende links, lijkt dit de conclusie:

De VDR is vooral een conceptueel iets en kan worden beschouwd als de scheidsrechter/mediator binnen een VC ecosysteem. Het speelt een rol bij het creëren en verifiëren van VC’s en andere relevante data zodat er voldoende vertrouwen ontstaat tussen de verschillende partijen binnen het ecosysteem. Een VDR kan o.a. informatie bevatten over VC schema’s, geregistreerde issuers en revocation lists. Ook kan een VDR alle transacties/uitgegeven VC’s bevatten, waarbij de persoonlijke gegevens zelf niet worden opgeslagen. Verschillende VC ecosystemen zullen verschillende VDR’s hebben waarbij bijv. de onderliggende techniek kan verschillen. Mogelijkheden zijn: “trusted databases, decentralized databases, government ID databases, and distributed ledgers”. Ook is het mogelijk dat er meerdere VDR’s worden gebruikt binnen één ecosysteem.

Links:
- [W3C VC data model](https://www.w3.org/TR/vc-data-model/)
- [Gitbhub issue over VDR](https://github.com/w3c/vc-data-model/issues/738)
- [Medium - Decentralized Identifiers](https://medium.com/metadium/decentralized-identifiers-personal-information-and-claims-the-easy-guide-ee58b5427dd2)
- [Artikel over VDR's](https://www.diva-portal.org/smash/get/diva2:1721096/FULLTEXT01.pdf)
- [SURF rapport over hun SSI onderzoek](https://www.surf.nl/files/2021-05/technical-exploration-surf-ledger-based-self-sovereign-identity.pdf)

**Comment by marcvanandel** [comment]
Ja, een **Verifiable Data Registry** is randvoorwaardelijk aan een goede werking van VCs ... over meerdere issues en verifiers. Daarvoor hebben we meer info beschreven in onze [documentatie](https://github.com/kadaster-labs/solid-quest/blob/main/Background.md#verifiable-data-registry). Daarbij is het ook duidelijk dat dit een brede behoefte en vele belangen heeft ... en dat wij vanuit onze quest daar geen invloed op uit kunnen oefenen. Daarom sluit ik het issue voor ons. Het is wel een ontwikkeling die we moeten blijven volgen.
