### ISSUE TITLE
Als koper wil ik met mijn Solid pod aan de Live demo van deze quest deelnemen

### ISSUE THREAD

**Issue by sgort** [kadaster-labs/solid-quest#57]
Nav https://github.com/MinBZK/regels.overheid.nl/issues/154 is er https://mijnsolidpod.nl/ gerealiseerd.

Nu zou ik graag met mijn Solid profile als **Koper** deel willen nemen aan de Solid Quest.

Mijn card https://mijnsolidpod.nl/steven/profile/card#me

**Comment by marcvanandel** [comment]
OK. We hebben hier wel pogingen toe ondernomen ... maar uiteindelijk hebben we er toch voor gekozen om vooral een demonstratie mogelijk te maken. Er is niet per se heel veel méér voor nodig om het breder te kunnen demonstreren ... maar wél is een `mock-overheid-server` nodig. Daarom hebben we toch niet de tijd gestoken in dit werkend maken. Instructies over hoe deze repo gestart en mee getest kan worden, zijn beschikbaar (of worden, as we speak, bijgewerkt!)

Wat we nog gaan opleveren, is een presentatie én een video waarin we achtergronden, toelichting en demo geven. Deze wordt ook (oa) hier in deze repo gepubliceerd en uiteraard op social media. Opvolging cq toelichting naar aanleiding van die publicatie is uiteraard in overleg mogelijk 😃 

Betekent dat we dit issue NIET gaan oplossen / aan voldoen. Daarom sluit ik deze nu.
